export const singleOrderItem = {
  sn: 1,
  xid: 'aXrLJbp7',
  item_id: 'Q1WR5vbm',
  name: 'Samsung Galaxy M32 5G',
  image: '71os5DRhuSL._AC_UY218_.jpg',
  image_url:
    'https://demo.stockifly.in/uploads/products/71os5DRhuSL._AC_UY218_.jpg',
  x_tax_id: '',
  discount_rate: 0,
  total_discount: 0,
  total_tax: 0,
  unit_price: 32.25,
  single_unit_price: 32.25,
  subtotal: 2580,
  quantity: 80,
  tax_rate: 0,
  tax_type: 'exclusive',
  x_unit_id: 'AdWNDqgV',
  unit: {
    company_id: 1,
    name: 'piece',
    short_name: 'pc',
    base_unit: null,
    operator: 'multiply',
    operator_value: '1',
    is_deletable: 0,
    created_at: null,
    updated_at: null,
    xid: 'AdWNDqgV',
  },
  stock_quantity: 80,
  unit_short_name: 'pc',
};

export const singleOrderItem2 = {
  sn: 2,
  xid: 'yMWXPWGQ',
  item_id: 'LjrYgXb5',
  name: 'Zebronics Bluetooth Soundbar',
  image: '813oEQBqFL._AC_UL604_SR604,400_.jpg',
  image_url:
    'https://demo.stockifly.in/uploads/products/813oEQBqFL._AC_UL604_SR604,400_.jpg',
  x_tax_id: '',
  discount_rate: 0,
  total_discount: 0,
  total_tax: 0,
  unit_price: 31,
  single_unit_price: 31,
  subtotal: 31,
  quantity: 1,
  tax_rate: 0,
  tax_type: 'exclusive',
  x_unit_id: 'AdWNDqgV',
  unit: {
    company_id: 1,
    name: 'piece',
    short_name: 'pc',
    base_unit: null,
    operator: 'multiply',
    operator_value: '1',
    is_deletable: 0,
    created_at: null,
    updated_at: null,
    xid: 'AdWNDqgV',
  },
  stock_quantity: 76,
  unit_short_name: 'pc',
};

export const singleOrderItem3 = {
  sn: 3,
  xid: '7ZWDkbpO',
  item_id: 'A8qA6Ebo',
  name: 'Sony Over-Ear Headphones',
  image: '715hXtbXdzL._AC_UY218_.jpg',
  image_url:
    'https://demo.stockifly.in/uploads/products/715hXtbXdzL._AC_UY218_.jpg',
  x_tax_id: '',
  discount_rate: 0,
  total_discount: 0,
  total_tax: 0,
  unit_price: 11,
  single_unit_price: 11,
  subtotal: 11,
  quantity: 1,
  tax_rate: 0,
  tax_type: 'exclusive',
  x_unit_id: 'AdWNDqgV',
  unit: {
    company_id: 1,
    name: 'piece',
    short_name: 'pc',
    base_unit: null,
    operator: 'multiply',
    operator_value: '1',
    is_deletable: 0,
    created_at: null,
    updated_at: null,
    xid: 'AdWNDqgV',
  },
  stock_quantity: 13,
  unit_short_name: 'pc',
};

export const orderItemsData = [
  singleOrderItem,
  singleOrderItem2,
  singleOrderItem3,
];

export const singleOrder = {
  unique_id: 'tG0zl9ZY1H3pMZeFt9rN',
  invoice_number: '5434654654',
  order_type: 'sales',
  order_date: '2024-01-31T06:19:52+00:00',
  tax_amount: 258,
  discount: 0,
  shipping: 0,
  subtotal: 2580,
  paid_amount: 2838,
  due_amount: 0,
  order_status: 'processing',
  payment_status: 'paid',
  total: 2838,
  tax_rate: 10,
  cancelled: 0,
  terms_condition:
    '1. Goods once sold will not be taken back or exchanged\n\t2. All disputes are subject to [ENTER_YOUR_CITY_NAME] jurisdiction only',
  xid: '8Vbnderk',
  x_warehouse_id: 'AdWNDqgV',
  x_from_warehouse_id: null,
  x_staff_user_id: 'AdWNDqgV',
  x_user_id: '3BrZZXrA',
  warehouse: {
    name: 'Electronifly',
    xid: 'AdWNDqgV',
  },
  from_warehouse: null,
  staff_member: {
    name: 'Admin',
    profile_image: null,
    user_type: 'staff_members',
    xid: 'AdWNDqgV',
    profile_image_url: 'https://demo.stockifly.in/images/user.png',
  },
  user: {
    user_type: 'customers',
    name: 'Arielle Franecki',
    profile_image: null,
    phone: '+16024298929',
    xid: '3BrZZXrA',
    profile_image_url: 'https://demo.stockifly.in/images/user.png',
  },
  order_payments: [
    {
      amount: 2838,
      xid: 'mKbKobL7',
      x_payment_id: 'mKbKobL7',
      payment: {
        amount: 2838,
        date: '2024-01-31T00:00:00+00:00',
        notes: null,
        xid: 'mKbKobL7',
        x_payment_mode_id: '7ZWDkbpO',
        payment_mode: {
          name: 'Paypal',
          xid: '7ZWDkbpO',
        },
      },
    },
  ],
  items: [
    {
      single_unit_price: 32.25,
      unit_price: 32.25,
      quantity: 80,
      tax_rate: 0,
      total_tax: 0,
      tax_type: 'exclusive',
      total_discount: 0,
      subtotal: 2580,
      xid: 'Q1WR5vbm',
      x_product_id: 'aXrLJbp7',
      product: {
        name: 'Samsung Galaxy M32 5G',
        image: '71os5DRhuSL._AC_UY218_.jpg',
        xid: 'aXrLJbp7',
        x_unit_id: 'AdWNDqgV',
        image_url:
          'https://demo.stockifly.in/uploads/products/71os5DRhuSL._AC_UY218_.jpg',
        unit: {
          name: 'piece',
          short_name: 'pc',
          xid: 'AdWNDqgV',
        },
        details: {
          current_stock: 0,
          xid: 'aXrLJbp7',
          x_warehouse_id: 'AdWNDqgV',
          x_product_id: 'aXrLJbp7',
          x_tax_id: null,
        },
      },
      order_item_taxes: [],
    },
  ],
  shipping_address: null,
};

export const singleOrder2 = {
  unique_id: 'Tl4VwADYixCKSvnzjGHz',
  invoice_number: 'SALE-94',
  order_type: 'sales',
  order_date: '2024-01-31T12:01:45+00:00',
  tax_amount: 0,
  discount: 0,
  shipping: 0,
  subtotal: 116,
  paid_amount: 1000,
  due_amount: -884,
  order_status: 'delivered',
  payment_status: 'paid',
  total: 116,
  tax_rate: 0,
  cancelled: 0,
  terms_condition: null,
  xid: 'dJb051WB',
  x_warehouse_id: 'AdWNDqgV',
  x_from_warehouse_id: null,
  x_staff_user_id: 'AdWNDqgV',
  x_user_id: 'dJb051WB',
  warehouse: {
    name: 'Electronifly',
    xid: 'AdWNDqgV',
  },
  from_warehouse: null,
  staff_member: {
    name: 'Admin',
    profile_image: null,
    user_type: 'staff_members',
    xid: 'AdWNDqgV',
    profile_image_url: 'https://demo.stockifly.in/images/user.png',
  },
  user: {
    user_type: 'customers',
    name: 'Walk In Customer',
    profile_image: null,
    phone: '+911111111111',
    xid: 'dJb051WB',
    profile_image_url: 'https://demo.stockifly.in/images/user.png',
  },
  order_payments: [
    {
      amount: 1000,
      xid: 'GLWy4boZ',
      x_payment_id: 'GLWy4boZ',
      payment: {
        amount: 1000,
        date: '2024-01-31T12:01:45+00:00',
        notes: null,
        xid: 'GLWy4boZ',
        x_payment_mode_id: 'AdWNDqgV',
        payment_mode: {
          name: 'Cash',
          xid: 'AdWNDqgV',
        },
      },
    },
  ],
  items: [
    {
      single_unit_price: 34,
      unit_price: 34,
      quantity: 1,
      tax_rate: 0,
      total_tax: 0,
      tax_type: 'exclusive',
      total_discount: 0,
      subtotal: 34,
      xid: '59bxykWO',
      x_product_id: 'NArJeWyE',
      product: {
        name: 'Apple EarPods',
        image: '51UEOS6bML._AC_UY218_.jpg',
        xid: 'NArJeWyE',
        x_unit_id: 'AdWNDqgV',
        image_url:
          'https://demo.stockifly.in/uploads/products/51UEOS6bML._AC_UY218_.jpg',
        unit: {
          name: 'piece',
          short_name: 'pc',
          xid: 'AdWNDqgV',
        },
        details: {
          current_stock: 68,
          xid: 'NArJeWyE',
          x_warehouse_id: 'AdWNDqgV',
          x_product_id: 'NArJeWyE',
          x_tax_id: null,
        },
      },
      order_item_taxes: [],
    },
    {
      single_unit_price: 41,
      unit_price: 41,
      quantity: 2,
      tax_rate: 0,
      total_tax: 0,
      tax_type: 'exclusive',
      total_discount: 0,
      subtotal: 82,
      xid: 'ZebQBBW6',
      x_product_id: 'AdWNDqgV',
      product: {
        name: 'Sony Noise Cancelling Headphones',
        image: '61njwOtQSML._AC_UY218_.jpg',
        xid: 'AdWNDqgV',
        x_unit_id: 'AdWNDqgV',
        image_url:
          'https://demo.stockifly.in/uploads/products/61njwOtQSML._AC_UY218_.jpg',
        unit: {
          name: 'piece',
          short_name: 'pc',
          xid: 'AdWNDqgV',
        },
        details: {
          current_stock: 103,
          xid: 'AdWNDqgV',
          x_warehouse_id: 'AdWNDqgV',
          x_product_id: 'AdWNDqgV',
          x_tax_id: null,
        },
      },
      order_item_taxes: [],
    },
  ],
  shipping_address: null,
};

export const ordersData = [singleOrder];

export const product1 = {
  name: 'S21 Pro',
  slug: 's21-pro',
  product_type: 'single',
  barcode_symbology: 'CODE128',
  item_code: '6786883',
  image: null,
  description: null,
  xid: '19q68AWa',
  image_url: 'https://demo.stockifly.in/images/product.png',
  x_category_id: 'M6q8vWzR',
  x_brand_id: 'AdWNDqgV',
  x_unit_id: 'AdWNDqgV',
  x_warehouse_id: 'AdWNDqgV',
  category: {
    name: 'Mobiles',
    xid: 'M6q8vWzR',
  },
  brand: {
    name: 'Sony',
    xid: 'AdWNDqgV',
  },
  unit: {
    name: 'piece',
    short_name: 'pc',
    xid: 'AdWNDqgV',
  },
  details: {
    stock_quantitiy_alert: 10,
    opening_stock: 20,
    opening_stock_date: null,
    wholesale_price: null,
    wholesale_quantity: null,
    mrp: 800,
    purchase_price: 650,
    sales_price: 700,
    purchase_tax_type: 'exclusive',
    sales_tax_type: 'exclusive',
    current_stock: 20,
    status: 'in_stock',
    x_warehouse_id: 'AdWNDqgV',
    x_tax_id: 'xJWzJLWN',
    tax: {
      name: 'GST',
      rate: 17,
      xid: 'xJWzJLWN',
      x_parent_id: null,
    },
    warehouse: {
      name: 'Electronifly',
      xid: 'AdWNDqgV',
      x_company_id: null,
      logo_url: 'https://demo.stockifly.in/images/warehouse.png',
      dark_logo_url: 'https://demo.stockifly.in/images/warehouse_dark.png',
      signature_url: null,
    },
  },
  custom_fields: [],
  warehouse: {
    xid: 'AdWNDqgV',
  },
};

export const product2 = {
  name: 'Coca Cola Zero PET 0.5',
  slug: 'coca-cola-zero-pet-05-18s9fib9',
  product_type: 'single',
  barcode_symbology: 'CODE128',
  item_code: '8788888877',
  image: null,
  description: null,
  xid: '59bxvXrO',
  image_url: 'https://demo.stockifly.in/images/product.png',
  x_category_id: '6ybkZq3D',
  x_brand_id: null,
  x_unit_id: 'AdWNDqgV',
  x_warehouse_id: 'AdWNDqgV',
  category: {
    name: 'Napoje',
    xid: '6ybkZq3D',
  },
  brand: null,
  unit: {
    name: 'piece',
    short_name: 'pc',
    xid: 'AdWNDqgV',
  },
  details: {
    stock_quantitiy_alert: 40,
    opening_stock: 34,
    opening_stock_date: '2024-01-10',
    wholesale_price: null,
    wholesale_quantity: null,
    mrp: 0,
    purchase_price: 19.9,
    sales_price: 39,
    purchase_tax_type: 'exclusive',
    sales_tax_type: 'inclusive',
    current_stock: 34,
    status: 'out_of_stock',
    x_warehouse_id: 'AdWNDqgV',
    x_tax_id: 'eJWGYyqo',
    tax: {
      name: 'VAT',
      rate: 10,
      xid: 'eJWGYyqo',
      x_parent_id: null,
    },
    warehouse: {
      name: 'Electronifly',
      xid: 'AdWNDqgV',
      x_company_id: null,
      logo_url: 'https://demo.stockifly.in/images/warehouse.png',
      dark_logo_url: 'https://demo.stockifly.in/images/warehouse_dark.png',
      signature_url: null,
    },
  },
  custom_fields: [
    {
      field_name: 'Expiry Date',
      field_value: null,
      xid: '7ZWDeQrp',
    },
  ],
  warehouse: {
    xid: 'AdWNDqgV',
  },
};

export const product3 = {
  name: 'Sauder Barrister Lane Executive Desk',
  slug: 'sauder-barrister-lane-executive-desk',
  product_type: 'single',
  barcode_symbology: 'CODE128',
  item_code: '8410179018232',
  image: '81sqJgoTVmL._AC_UL320_.jpg',
  description: null,
  xid: 'ZebQwgr6',
  image_url:
    'https://demo.stockifly.in/uploads/products/81sqJgoTVmL._AC_UL320_.jpg',
  x_category_id: 'aJrgKrl1',
  x_brand_id: 'zJr3jWeQ',
  x_unit_id: 'AdWNDqgV',
  x_warehouse_id: null,
  category: {
    name: 'Home and Furnitures',
    xid: 'aJrgKrl1',
  },
  brand: {
    name: 'Sauder',
    xid: 'zJr3jWeQ',
  },
  unit: {
    name: 'piece',
    short_name: 'pc',
    xid: 'AdWNDqgV',
  },
  details: {
    stock_quantitiy_alert: 25,
    opening_stock: 43,
    opening_stock_date: null,
    wholesale_price: null,
    wholesale_quantity: null,
    mrp: 39,
    purchase_price: 33,
    sales_price: 37,
    purchase_tax_type: 'exclusive',
    sales_tax_type: 'exclusive',
    current_stock: 49,
    status: 'in_stock',
    x_warehouse_id: 'AdWNDqgV',
    x_tax_id: null,
    tax: null,
    warehouse: {
      name: 'Electronifly',
      xid: 'AdWNDqgV',
      x_company_id: null,
      logo_url: 'https://demo.stockifly.in/images/warehouse.png',
      dark_logo_url: 'https://demo.stockifly.in/images/warehouse_dark.png',
      signature_url: null,
    },
  },
  custom_fields: [],
  warehouse: null,
};

export const product4 = {
  name: 'Sauder Costa Lateral File',
  slug: 'sauder-costa-lateral-file',
  product_type: 'single',
  barcode_symbology: 'CODE128',
  item_code: '4052879612',
  image: '81QV3GYz4zL._AC_UL320_.jpg',
  description: null,
  xid: '2abBpdrw',
  image_url:
    'https://demo.stockifly.in/uploads/products/81QV3GYz4zL._AC_UL320_.jpg',
  x_category_id: 'aJrgKrl1',
  x_brand_id: 'zJr3jWeQ',
  x_unit_id: 'AdWNDqgV',
  x_warehouse_id: null,
  category: {
    name: 'Home and Furnitures',
    xid: 'aJrgKrl1',
  },
  brand: {
    name: 'Sauder',
    xid: 'zJr3jWeQ',
  },
  unit: {
    name: 'piece',
    short_name: 'pc',
    xid: 'AdWNDqgV',
  },
  details: {
    stock_quantitiy_alert: 20,
    opening_stock: 74,
    opening_stock_date: null,
    wholesale_price: null,
    wholesale_quantity: null,
    mrp: 49,
    purchase_price: 43,
    sales_price: 45,
    purchase_tax_type: 'exclusive',
    sales_tax_type: 'exclusive',
    current_stock: 74,
    status: 'in_stock',
    x_warehouse_id: 'AdWNDqgV',
    x_tax_id: null,
    tax: null,
    warehouse: {
      name: 'Electronifly',
      xid: 'AdWNDqgV',
      x_company_id: null,
      logo_url: 'https://demo.stockifly.in/images/warehouse.png',
      dark_logo_url: 'https://demo.stockifly.in/images/warehouse_dark.png',
      signature_url: null,
    },
  },
  custom_fields: [],
  warehouse: null,
};

export const product5 = {
  name: 'Furinno Frame Computer Desk',
  slug: 'furinno-frame-computer-desk',
  product_type: 'single',
  barcode_symbology: 'CODE128',
  item_code: '4126377433',
  image: '71mJ-owgDlL._AC_UL320_.jpg',
  description: null,
  xid: 'ZLr9PVWe',
  image_url:
    'https://demo.stockifly.in/uploads/products/71mJ-owgDlL._AC_UL320_.jpg',
  x_category_id: 'aJrgKrl1',
  x_brand_id: 'xaWoaqgG',
  x_unit_id: 'AdWNDqgV',
  x_warehouse_id: null,
  category: {
    name: 'Home and Furnitures',
    xid: 'aJrgKrl1',
  },
  brand: {
    name: 'Furinno',
    xid: 'xaWoaqgG',
  },
  unit: {
    name: 'piece',
    short_name: 'pc',
    xid: 'AdWNDqgV',
  },
  details: {
    stock_quantitiy_alert: 45,
    opening_stock: 40,
    opening_stock_date: null,
    wholesale_price: null,
    wholesale_quantity: null,
    mrp: 49,
    purchase_price: 43,
    sales_price: 45,
    purchase_tax_type: 'exclusive',
    sales_tax_type: 'exclusive',
    current_stock: 129,
    status: 'in_stock',
    x_warehouse_id: 'AdWNDqgV',
    x_tax_id: null,
    tax: null,
    warehouse: {
      name: 'Electronifly',
      xid: 'AdWNDqgV',
      x_company_id: null,
      logo_url: 'https://demo.stockifly.in/images/warehouse.png',
      dark_logo_url: 'https://demo.stockifly.in/images/warehouse_dark.png',
      signature_url: null,
    },
  },
  custom_fields: [],
  warehouse: null,
};

export const product6 = {
  name: 'Furinno Office Computer Desk',
  slug: 'furinno-office-computer-desk',
  product_type: 'single',
  barcode_symbology: 'CODE128',
  item_code: '2437665666',
  image: '71MUVgvmJIL._AC_UL320_.jpg',
  description: null,
  xid: 'XAW57Bqo',
  image_url:
    'https://demo.stockifly.in/uploads/products/71MUVgvmJIL._AC_UL320_.jpg',
  x_category_id: 'aJrgKrl1',
  x_brand_id: 'xaWoaqgG',
  x_unit_id: 'AdWNDqgV',
  x_warehouse_id: null,
  category: {
    name: 'Home and Furnitures',
    xid: 'aJrgKrl1',
  },
  brand: {
    name: 'Furinno',
    xid: 'xaWoaqgG',
  },
  unit: {
    name: 'piece',
    short_name: 'pc',
    xid: 'AdWNDqgV',
  },
  details: {
    stock_quantitiy_alert: 50,
    opening_stock: 86,
    opening_stock_date: null,
    wholesale_price: null,
    wholesale_quantity: null,
    mrp: 79,
    purchase_price: 53,
    sales_price: 65,
    purchase_tax_type: 'exclusive',
    sales_tax_type: 'exclusive',
    current_stock: 104,
    status: 'in_stock',
    x_warehouse_id: 'AdWNDqgV',
    x_tax_id: null,
    tax: null,
    warehouse: {
      name: 'Electronifly',
      xid: 'AdWNDqgV',
      x_company_id: null,
      logo_url: 'https://demo.stockifly.in/images/warehouse.png',
      dark_logo_url: 'https://demo.stockifly.in/images/warehouse_dark.png',
      signature_url: null,
    },
  },
  custom_fields: [],
  warehouse: null,
};

export const productsData = [
  product1,
  product2,
  product3,
  product4,
  product5,
  product6,
];
